INSERT INTO categorie (nom,parent) VALUES ('Produits','');
INSERT INTO categorie (nom,parent) VALUES ('Ordinateurs','Produits');
INSERT INTO categorie (nom,parent) VALUES ('Meubles','Produits');
INSERT INTO categorie (nom,parent) VALUES ('Livres','Produits');
INSERT INTO categorie (nom,parent) VALUES ('Ordinateurs Portbales','Ordinateurs');
INSERT INTO categorie (nom,parent) VALUES ('Ordinateurs Fixes','Ordinateurs');
INSERT INTO categorie (nom,parent) VALUES ('Lits','Meubles');
INSERT INTO categorie (nom,parent) VALUES ('Tables','Meubles');
INSERT INTO categorie (nom,parent) VALUES ('Romans','Livres');
INSERT INTO categorie (nom,parent) VALUES ('Policier','Romans');
